steps:
  - name: 'gcr.io/cloud-builders/go:alpine'
    env: ['PROJECT_ROOT=gke-playground-201706']
    args: ['build', '-o', 'api', 'main.go']
  - name: 'gcr.io/cloud-builders/docker'
    env: ['PROJECT_ROOT=gke-playground-201706']
    args: ['build', '--tag=gcr.io/$PROJECT_ID/api', '.']
images: ['gcr.io/$PROJECT_ID/api']
