apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-app
        image: gcr.io/gke-playground-201706/helloworld:latest
        imagePullPolicy: Always
        ports:
          - name: http-server
            containerPort: 8080
